---
# tasks file for ./ansible/roles/common
- name: Apt Update
  apt: update_cache=yes cache_valid_time=3600

- name: Apt Upgrade
  apt: upgrade=dist

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - tree
    - git
